### ISSUE TITLE
Differences from server

### ISSUE THREAD

**Issue by coil0** [pandorabox-io/pandorabox-mods#1]
- [x] Missing nil check for item stack in on_rightclick for anvil
- [x] atm is missing the nil check in [atm.patch](https://github.com/pandorabox-io/pandorabox-mods/files/3506664/atm.txt)
- [x] Different recipe for banners:steel_pole
- [x] Different recipe for castle_weapons:crossbow_bolt
- [x] ccompass is missing throttling and a fix for conflicting recipe with digtron
- [x] Recipe for charcoal uses group:tree instead of group:wood
- [x] Income is enabled in the currency mod (it's commented on the server); however, income is [configurable](https://gitlab.com/VanessaE/currency/blob/d208628a2d26fd9906f1c9af6e0966487469c98b/income.lua#L7) upstream now so there's no need to create a fork
- [x] fancy_vend has mail enabled (and probably not working)
- [x] loot has a lower interval (1 instead of 2) for the loot:loot_node ABM (**non-isue**: i think i was just experimenting there)
- [x] mobs_animal is missing change on server for breeding penguin
- [ ] moreblocks is missing changes in [moreblocks.patch](https://github.com/pandorabox-io/pandorabox-mods/files/3506107/moreblocks.txt)
- [x] pandorabox_custom is missing changes in [pandorabox_custom.patch](https://github.com/pandorabox-io/pandorabox-mods/files/3506108/pandorabox_custom.txt)
- [x] In prefab, electric fence damage is 30 instead of 2
- [ ] replacer is missing patch for placing in vacuum
- [x] smartrenting is missing change to comment `override_items.lua`
- [x] spawn_command is missing changes in [spawn_command.patch](https://github.com/pandorabox-io/pandorabox-mods/files/3506109/spawn_command.txt) (embedded dep: https://github.com/pandorabox-io/pandorabox_custom/commit/002460c7ae6174a29ea721647c23304725041ae1)
- [ ] stamina is missing a few commits
- [x] unified_inventory_plus is missing changes in [unified_inventory_plus.patch](https://github.com/pandorabox-io/pandorabox-mods/files/3506110/unified_inventory_plus.txt)
- [x] vines is missing changes in [vines.patch](https://github.com/pandorabox-io/pandorabox-mods/files/3506111/vines.txt) (**non-issue**: nodetimers were not the problem)
- [x] woodcutting is missing changes in [woodcutting.patch](https://github.com/pandorabox-io/pandorabox-mods/files/3506112/woodcutting.txt)
- [x] xp_redo is missing changes to comment xp loss on death
- [ ] biomelib is disabled on the current server
- [x] This repo has more recent commits for fancy_vend, farming_nextgen, homedecor_modpack, ilights, jumpdrive, led_marquee, mail, mesecons_stealthnode, missions, moretrees, planetoidgen, signs_lib, spacecannon, tpr, wine

**Comment by thomasrudin** [comment]
Oh my, that stuff accumulated over time :/
I'll comment on this when i'm doing work on that...

Another thing: I separated the `mt_auth` repo into app and mod (https://github.com/pandorabox-io/pandorabox-mods/commit/b618d3e2832437c0e995ebf65e03f544510be95a), is it ok if we move the submodules to the root path?

**Comment by coil0** [comment]
Yes, but then we’d have all of plantlife_modpack. The symlink picks out just plantlife_i18n. Otherwise, it’d be nice to get rid of the symlinks since world.mt can already be used to enable and disable mods.

**Comment by thomasrudin** [comment]
I removed the `smartrenting` mod completely, this thing was buggy to begin with and to no real use.

**Comment by coil0** [comment]
> Missing nil check for item stack in on_rightclick for anvil

Seems impossible for itemstack to be nil unless a mod calls `minetest.item_place` with nil. Even then, it would still crash a few lines later if there was no placer because builtin also assumes itemstack is not nil.

> xp_redo is missing changes to comment xp loss on death

Can be replaced by thomasrudin-mt/xp_redo#33.

**Comment by thomasrudin** [comment]
> > Missing nil check for item stack in on_rightclick for anvil
> 
> Seems impossible for itemstack to be nil unless a mod calls `minetest.item_place` with nil. Even then, it would still crash a few lines later if there was no placer because builtin also assumes itemstack is not nil.

Oh, that was the "anvil of doom" issue: the travelnet tries to do a rightclick on nearby nodes: https://github.com/Sokomine/travelnet/blob/master/init.lua#L654

> > xp_redo is missing changes to comment xp loss on death
> 
> Can be replaced by [thomasrudin-mt/xp_redo#33](https://github.com/thomasrudin-mt/xp_redo/pull/33).

Thx, merged :)

I'll test the new meta-repo on the test-server (test.pandorabox.io) but can we merge #2 before that?

**Comment by coil0** [comment]
> Oh, that was the "anvil of doom" issue: the travelnet tries to do a rightclick on nearby nodes: https://github.com/Sokomine/travelnet/blob/master/init.lua#L654

Submitted a fix (to anvil, even though it's really travelnet that needs fixed).

> I'll test the new meta-repo on the test-server (test.pandorabox.io) but can we merge #2 before that?

Yes, I merged #4.

**Comment by thomasrudin** [comment]
I switched the protector mod to tenplus1's original one again, my only local modification was some warning if the globalstep took too long

**Comment by thomasrudin** [comment]
woodcutting upstream issue: https://github.com/minetest-mods/woodcutting/pull/4

**Comment by thomasrudin** [comment]
prefab setting: https://github.com/minetest-mods/prefab/pull/4

**Comment by thomasrudin** [comment]
Unified inventory settings: https://github.com/bousket/unified_inventory_plus/pull/2

**Comment by thomasrudin** [comment]
@coil0 about the replacer commits: should we switch to your branch or do you want to wait for the PR to be merged?

**Comment by coil0** [comment]
#10 switches to my branch. If the upstream PR does not get merged, we could switch to HybridDog's fork, which has other improvements for creative and doesn't break metadata.

**Comment by thomasrudin** [comment]
closing due to installement of the repo, thx for the help @coil0 :+1:
