### ISSUE TITLE
.gitmodules order

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/pandorabox-mods#1183]
Is there a particular reason the repos are not all in alphabetical order? Do I have permission to sort them by mod name?

Sure can use search functions, and most interfaces will sort for us.

**Comment by OgelGames** [comment]
When it was created it was in order ([here](https://github.com/pandorabox-io/pandorabox-mods/blob/cb1d6617f8b412af95ce093d471bc6e9d6a59202/.gitmodules)), but all the mods added after were just added to the end 😄 

Should be fine to sort it again, if you think it needs it...

**Comment by BuckarooBanzay** [comment]
> Do I have permission to sort them by mod name?

Sure thing, we may have to rebase some pr's after this but that won't be painful :yum:

**Comment by OgelGames** [comment]
Fixed by #1184
