### ISSUE TITLE
Remove textbook/git-checkout-submodule-action

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox-mods#1192]
Is there any reason to have `textbook/git-checkout-submodule-action@2.0.0` for integration tests?
`actions/checkout@v2` is already there too and it should handle this a lot better with `submodules: recursive` switch unless I missed something.

actions/checkout is bit more intelligent when it comes to submodules, also removing textbook/git-checkout-submodule-action reduces dependencies.

Should fix this (reason why I looked at job definition): #1191

**Comment by BuckarooBanzay** [comment]
> actions/checkout@v2 is already there too and it should handle this a lot better with submodules: recursive switch unless I missed something.

i think that was the only viable option back then :thinking:
