### ISSUE TITLE
Add mirror for basic_trains

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox-mods#1636]
Advtrains comes from mirror repository minetest-mirrors/advtrains, should basic trains also be mirrored at minetest-mirrors/basic_trains?

```
[submodule "basic_trains"]
	path = basic_trains
	url = https://git.bananach.space/basic_trains.git
```

**Comment by BuckarooBanzay** [comment]
i prepared that already, switched to the mirror repo now :+1:
