### ISSUE TITLE
Add Hammermod

### ISSUE THREAD

**Issue by Monniasza** [pandorabox-io/pandorabox-mods#2867]
I'd like to have Hammer mod added, to speed up mining:
https://content.minetest.net/packages/cultom/hammermod/

**Comment by BuckarooBanzay** [comment]
I'm not sure about this, we already have the mining-drills and lasers and those are technic-enabled

Does the hammer in that mod even wear out? :thinking:

**Comment by S-S-X** [comment]
See linked issue:
* https://github.com/pandorabox-io/in-game/issues/315
