### ISSUE TITLE
Update Beerchat 

### ISSUE THREAD

**Issue by Monniasza** [pandorabox-io/pandorabox-mods#3022]
Hi, The Beerchat has fixed crash when typing `/tell` with no arguments at https://github.com/mt-mods/beerchat/pull/113.
Please update Beerchat and restart the server to apply changes.

**Comment by S-S-X** [comment]
Mod updates are semi automatically handled by dependabot, didn't start manual run as so far this didn't seem to cause big issues with server.
I guess I could do that, then any of the moderators in game can restart or it restarts when someone crashes it 🤷
